export const plannetImages = [
  { name: 'Earth',
    url: 'https://space-facts.com/wp-content/uploads/earth-transparent-300x300.png'},
  { name: 'Mercury',
    url: 'https://space-facts.com/wp-content/uploads/mercury-transparent-300x300.png'},
  { name: 'Venus',
    url: 'https://space-facts.com/wp-content/uploads/venus-transparent-300x300.png'},
  { name: 'Mars',
    url: 'https://space-facts.com/wp-content/uploads/mars-transparent-300x300.png'},
  { name: 'Jupiter',
    url: 'https://space-facts.com/wp-content/uploads/jupiter-transparent-300x300.png'},
  { name: 'Saturn',
    url: 'https://space-facts.com/wp-content/uploads/saturn-transparent-300x300.png'},
  { name: 'Uranus',
    url: 'https://space-facts.com/wp-content/uploads/uranus-transparent-300x300.png'},
  { name: 'Neptune',
    url: 'https://space-facts.com/wp-content/uploads/neptune-transparent-300x300.png'},
  { name: 'Sun',
    url: 'https://space-facts.com/wp-content/uploads/sun-transparent-300x300.png'},
  { name: 'Moon',
    url: 'https://space-facts.com/wp-content/uploads/moon-transparent-300x300.png'}
]
